{{- if .Values.secret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcp.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
{{- with .Values.secret.data }}
stringData:
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
