---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port | int }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mcp.selectorLabels" . | nindent 4 }}
